version: "3.9"

services:
    web:
        container_name: sandbox_app
        build:
            context: ./docker/web
        volumes:
            - type: bind
              source: .
              target: /var/www/sites/laravel-sandbox.com
        working_dir: /var/www/sites/laravel-sandbox.com
        ports:
            - ${WEB_HOSTNAME:-127.0.0.1}:${WEB_HOSTNAME_PORT:-80}:80
        tty: true
        stdin_open: true
        depends_on:
            - db
        env_file:
            - .env
        networks:
            app_network:
                ipv4_address: ${IPV4_NETWORK:-172.25.2}.10
                aliases:
                    - application

    db:
        container_name: sandbox_app_db
        platform: linux/amd64 # needed for macos
        build:
            context: ./docker/mysql
        ports:
            - ${DATABASE_HOST:-127.0.0.1}:${DATABASE_HOST_PORT:-3306}:3306
        volumes:
            - data:/var/lib/mysql/
        env_file:
            - ./docker/mysql/vars.env
        networks:
            app_network:
                ipv4_address: ${IPV4_NETWORK:-172.25.2}.11
                aliases:
                    - database

    redis:
        container_name: sandbox_app_redis
        build:
            context: ./docker/redis
        restart: always
        deploy:
            resources:
                limits:
                    memory: 128M
        ports:
            - ${REDIS_PORT:-6379}:6379
        volumes:
            - ./docker/redis/redis.conf:/etc/redis.conf
            - redis_data:/storage
        networks:
            app_network:
                ipv4_address: ${IPV4_NETWORK:-172.25.2}.12
                aliases:
                    - redis_store

volumes:
    data:
        driver: local
    redis_data:
        driver: local
        driver_opts:
            type: "none"
            o: "bind"
            device: "./docker/redis/storage"

networks:
    app_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${IPV4_NETWORK:-172.25.2}.0/24
                  gateway: ${IPV4_NETWORK:-172.25.2}.1
